import { Product } from './product.model';

export const PRODUCTS: Product[] = [
    // Phones
    {
        id: 1,
        name: 'iPhone 13 Pro Max',
        price: 999,
        description: '6.1-inch Super Retina XDR display with ProMotion.',
        imageUrl: 'img/phone-iphone.jpg',
        category: 'Electronics',
        rating: 4.7,
        brand: 'Apple',
        quantity: 1,
        availability: true,
    },
    {
        id: 2,
        name: 'Samsung Galaxy S23',
        price: 899,
        description: 'Dynamic AMOLED display, Snapdragon processor.',
        imageUrl: 'img/phone-samsung.jpg',
        category: 'Electronics',
        rating: 4.5,
        brand: 'Samsung',
        quantity: 1,
        availability: true,
    },
    {
        id: 3,
        name: 'Huawei P50 Pro',
        price: 849,
        description: 'Ultra Vision Camera, powerful performance.',
        imageUrl: 'img/phone-huawei.jpg',
        category: 'Electronics',
        rating: 4.4,
        brand: 'Huawei',
        quantity: 1,
        availability: false,
    },

    // Headphones
    {
        id: 4,
        name: 'Sony WH-1000XM5 Headphones',
        price: 399,
        description: 'Industry-leading noise cancellation with exceptional sound quality.',
        imageUrl: 'img/headphone-sony.jpg',
        category: 'Accessories',
        rating: 4.8,
        brand: 'Sony',
        quantity: 1,
        availability: true,
    },
    {
        id: 5,
        name: 'Sennheiser Momentum 4',
        price: 349,
        description: 'Crystal clear sound with adaptive noise cancellation.',
        imageUrl: 'img/headphones-senheiser.jpg',
        category: 'Accessories',
        rating: 4.6,
        brand: 'Sennheiser',
        quantity: 1,
        availability: false,
    },
    {
        id: 6,
        name: 'Bose QuietComfort 45',
        price: 329,
        description: 'Unmatched comfort with world-class noise cancellation.',
        imageUrl: 'img/headphones-bose.jpg',
        category: 'Accessories',
        rating: 4.7,
        brand: 'Bose',
        quantity: 1,
        availability: true,
    },

    // Laptops
    {
        id: 7,
        name: 'MacBook Pro 14"',
        price: 1999,
        description: 'M2 Pro chip, Liquid Retina XDR display.',
        imageUrl: 'img/laptop-macbook.jpg',
        category: 'Computers',
        rating: 4.9,
        brand: 'Apple',
        quantity: 1,
        availability: false,
    },
    {
        id: 8,
        name: 'HP Spectre x360',
        price: 1499,
        description: '13.5-inch OLED touch display, Intel Evo platform.',
        imageUrl: 'img/laptop-hp.jpg',
        category: 'Computers',
        rating: 4.6,
        brand: 'HP',
        quantity: 1,
        availability: true,
    },
    {
        id: 9,
        name: 'Acer Swift 3',
        price: 799,
        description: '14-inch FHD display, lightweight design.',
        imageUrl: 'img/laptop-acer.jpg',
        category: 'Computers',
        rating: 4.3,
        brand: 'Acer',
        quantity: 1,
        availability:true,
    }
];
